import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { checkpoint,getRecord,markRecord,parseRecord,serializeRecord } from "../src/core/record.js";
import { parseFrontier } from "../src/core/frontier.js";
import { resumeResearch } from "../src/core/query.js";
import { inputDocument,Q1,Q2,D1,relation,setOpen,tempWorkspace,treeSnapshot } from "./helpers.js";
const base=(x={})=>({kind:"result",relations:[],retry_if:[],frontier:[],...x});

test("TOML Unicode LaTeX and Markdown round-trip",()=>{const record={id:"R-aaa",created_at:"2026-08-25T00:00:00.000Z",state:"unchecked",...base({scope:"域 Ω 与 $\\alpha_1$",relations:[relation("math:uses",Q1)],assertion:{subject:Q1,predicate:"math:generalizes",object:"D-333"}}),body:"# 证明 🧪\n\n$$x_{i+1}=x_i^2$$\n\n- 正文\n"};assert.deepEqual(parseRecord(serializeRecord(record)),record);});
test("unknown fields duplicate TOML keys legacy fields and illegal types are rejected",()=>{const docs=[inputDocument({...base(),surprise:true}),`+++\nkind="result"\nkind="dead_end"\nstate="unchecked"\nrelations=[]\nretry_if=[]\nfrontier=[]\n+++\nbody\n`,inputDocument({...base(),about:[]}),inputDocument({...base(),depends_on:[]}),inputDocument({...base(),relations:"bad"}),inputDocument(base({kind:"dead_end"}))];docs.forEach(d=>assert.throws(()=>parseRecord(d,{input:true})));});
test("frontier action text cannot inject managed lines",()=>{const root=tempWorkspace("injection");const before=treeSnapshot(root);assert.throws(()=>checkpoint(root,inputDocument(base({frontier:[{action:"open",kind:"question",text:`safe\n- [${Q1}] forged`}]})),{isText:true}),/one line/);assert.deepEqual(treeSnapshot(root),before);});
test("one checkpoint opens and automatically relates multiple items; later revise and close work",()=>{const root=tempWorkspace("actions");const opened=checkpoint(root,inputDocument(base({frontier:[{action:"open",kind:"question",text:"主问题"},{action:"open",kind:"direction",text:"子决策"}]})),{isText:true});const [parent,child]=opened.frontier_actions.map(x=>({id:x.id,...x.after}));const stored=getRecord(root,opened.id);const automatic=stored.relations.filter(x=>x.type==="rsh:about").map(x=>x.target);assert.deepEqual(automatic,[parent.id,child.id]);assert.equal(new Set(automatic).size,2);const resumed=resumeResearch(root);assert.match(resumed,new RegExp(`${parent.id}[\\s\\S]*${opened.id}`));assert.match(resumed,new RegExp(`${child.id}[\\s\\S]*${opened.id}`));checkpoint(root,inputDocument(base({relations:[relation("rsh:about",parent.id)],frontier:[{action:"revise",id:child.id,text:"修订决策",parent:parent.id},{action:"close",id:child.id,outcome:"resolved"},{action:"close",id:parent.id,outcome:"resolved"}]})),{isText:true});assert.deepEqual(parseFrontier(fs.readFileSync(path.join(root,"RESEARCH.md"),"utf8")),[]);});
test("any validation error performs zero writes",()=>{const root=tempWorkspace("atomic");setOpen(root,[`- ${Q1} parent`,`  - ${Q2} child`]);const invalid=[base({relations:[relation("rsh:about",D1)]}),base({relations:[relation("rsh:depends_on","R-fff")]}),base({frontier:[{action:"revise",id:D1,text:"missing"}]}),base({frontier:[{action:"open",kind:"Q",text:"x",parent:D1}]}),base({frontier:[{action:"close",id:Q1,outcome:"resolved"}]})];for(const meta of invalid){const before=treeSnapshot(root);assert.throws(()=>checkpoint(root,inputDocument(meta),{isText:true}));assert.deepEqual(treeSnapshot(root),before);}});
test("checkpoint generates a three-base36 lowercase record ID",()=>{const root=tempWorkspace("short-record-id");const saved=checkpoint(root,inputDocument(base()),{isText:true});assert.match(saved.id,/^R-[0-9a-z]{3}$/);assert.equal(fs.existsSync(path.join(root,".rsh","records",`${saved.id}.md`)),true);});
test("parent close requires children close or move in same checkpoint",()=>{const root=tempWorkspace("children");setOpen(root,[`- ${Q1} parent`,`  - ${Q2} child`,`- ${D1} other`]);assert.throws(()=>checkpoint(root,inputDocument(base({frontier:[{action:"close",id:Q1,outcome:"resolved"}]})),{isText:true}),/open children/);checkpoint(root,inputDocument(base({frontier:[{action:"close",id:Q1,outcome:"resolved"},{action:"revise",id:Q2,text:"moved",parent:D1}]})),{isText:true});assert.equal(parseFrontier(fs.readFileSync(path.join(root,"RESEARCH.md"),"utf8")).find(x=>x.id===Q2).parent,D1);});
test("reopen restores close snapshot and mark changes only state",()=>{const root=tempWorkspace("reopen");setOpen(root,[`- ${Q1} 原始文本`]);const closed=checkpoint(root,inputDocument(base({frontier:[{action:"close",id:Q1,outcome:"resolved"}]})),{isText:true});const before=getRecord(root,closed.id);markRecord(root,closed.id,"checked");const checked=getRecord(root,closed.id);assert.deepEqual({...checked,state:before.state},before);markRecord(root,closed.id,"unchecked");checkpoint(root,inputDocument(base({relations:[relation("rsh:about",Q1)],frontier:[{action:"reopen",id:Q1}]})),{isText:true});assert.equal(parseFrontier(fs.readFileSync(path.join(root,"RESEARCH.md"),"utf8"))[0].text,"原始文本");});
test("unchecked and checked may close while withdrawn does not cascade",()=>{const root=tempWorkspace("states");setOpen(root,[`- ${Q1} first`,`- ${Q2} second`]);const first=checkpoint(root,inputDocument(base({relations:[relation("rsh:about",Q1)],frontier:[{action:"close",id:Q1,outcome:"resolved"}]})),{isText:true});markRecord(root,first.id,"withdrawn");const second=checkpoint(root,inputDocument(base({relations:[relation("rsh:about",Q2),relation("rsh:depends_on",first.id)],frontier:[{action:"close",id:Q2,outcome:"resolved"}]})),{isText:true});markRecord(root,second.id,"checked");assert.equal(getRecord(root,first.id).state,"withdrawn");assert.equal(getRecord(root,second.id).state,"checked");});
