import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { checkpoint,markRecord } from "../src/core/record.js";
import { findRecords,getItem,resumeResearch,statusWorkspace } from "../src/core/query.js";
import { doctor } from "../src/core/doctor.js";
import { inputDocument,Q1,Q2,relation,runCli,setOpen,tempWorkspace } from "./helpers.js";
const base=(x={})=>({kind:"result",relations:[],retry_if:[],frontier:[],...x});
function seed(root){setOpen(root,[`- ${Q1} 中文问题 alpha`,`- ${Q2} Regex target`]);const old=checkpoint(root,inputDocument(base({relations:[relation("rsh:about",Q1)]}),"# Old\n\n中文 $\\alpha$ fixed.* token\n"),{isText:true});const mid=checkpoint(root,inputDocument(base({kind:"experience",relations:[relation("rsh:about",Q1),relation("rsh:depends_on",old.id)]}),"# Mid\n\n中文 $\\beta$\n"),{isText:true});const recent=checkpoint(root,inputDocument(base({relations:[relation("rsh:about",Q1),relation("rsh:depends_on",old.id)]}),"# Recent\n\n中文 $\\gamma$\n"),{isText:true});checkpoint(root,inputDocument(base({kind:"dead_end",scope:"n>3",relations:[relation("rsh:about",Q1)],retry_if:["new lemma"]}),"# Fourth\n\n中文 $\\delta$\n"),{isText:true});markRecord(root,old.id,"withdrawn");return{old,mid,recent};}
test("resume directly augments RESEARCH with latest 3/all and withdrawn warning",()=>{const root=tempWorkspace("resume");const{old,recent}=seed(root);const normal=resumeResearch(root);assert.match(normal,new RegExp(recent.id));assert.doesNotMatch(normal,new RegExp(`^- \\*\\*${old.id}`,"m"));assert.ok(normal.includes(`1 more record(s): \`rsh find ${Q1}\``));assert.match(normal,new RegExp(`depends on withdrawn ${old.id}`));assert.match(resumeResearch(root,{all:true}),new RegExp(`^- \\*\\*${old.id}`,"m"));});
test("find uses rg for Unicode LaTeX fixed regex filters ID lookup and latest-first limits",()=>{const root=tempWorkspace("find");const{old}=seed(root);assert.ok(findRecords(root,"中文").length>=4);assert.ok(findRecords(root,"$\\alpha$").some(x=>x.id===old.id));assert.ok(findRecords(root,"fixed.*").some(x=>x.id===old.id));assert.ok(findRecords(root,"fixed.*",{regex:true}).some(x=>x.id===old.id));assert.ok(findRecords(root,"中文",{kind:"experience"}).every(x=>x.kind==="experience"));const related=findRecords(root,Q1);assert.deepEqual(new Set(related.map(x=>x.id)),new Set(findRecords(root,"中文").filter(x=>x.source==="record").map(x=>x.id)));assert.ok(related.every(x=>x.source==="record"));assert.ok(findRecords(root,"中文",{state:"withdrawn"}).every(x=>x.withdrawn));assert.equal(findRecords(root,Q1,{limit:1})[0].title,"Fourth");assert.match(runCli(root,["find",Q1]).stdout,/Fourth/);assert.match(runCli(root,["find","中文"],{env:{PATH:path.dirname(process.execPath)},success:false}).stderr,/rg search failed|ENOENT/);});
test("get status and doctor expose complete state",()=>{const root=tempWorkspace("read");const{old}=seed(root);assert.match(getItem(root,old.id),/\+\+\+[\s\S]*# Old[\s\S]*## RSH backlinks/);assert.match(getItem(root,Q1),/## Related records/);const status=statusWorkspace(root);assert.equal(status.frontier.open,2);assert.equal(status.records.total,4);assert.equal(doctor(root).ok,true);});
test("CLI has exact commands arity flags and stdin checkpoint",()=>{const root=tempWorkspace("cli");const help=runCli(root,["help"]).stdout;for(const c of ["init","resume","find","checkpoint","replace","delete","undo","get","mark","status","doctor","mcp","help","version"])assert.match(help,new RegExp(`rsh ${c}`));for(const old of ["seed","orient","check","record","import","diff"])assert.doesNotMatch(help,new RegExp(`rsh ${old}(?:\\s|$)`));assert.match(help,/rsh find QUERY/);assert.match(help,/rsh get ID/);assert.match(runCli(root,["get","--help"]).stdout,/Usage:/);assert.match(runCli(root,["find"],{success:false}).stderr,/exactly 1 positional|requires.*query/i);assert.match(runCli(root,["find",Q1,"extra"],{success:false}).stderr,/exactly 1 positional/);assert.match(runCli(root,["init","--name","unused"],{success:false}).stderr,/Unknown flag --name/);assert.match(runCli(root,["status","extra"],{success:false}).stderr,/exactly 0 positional/);assert.match(runCli(root,["resume","--regex"],{success:false}).stderr,/Unknown flag --regex for command resume/);assert.match(runCli(root,["mark","R-aaa","accepted"],{success:false}).stderr,/unchecked, checked, or withdrawn/);assert.match(runCli(root,["checkpoint","-"],{input:inputDocument(base())}).stdout,/R-[0-9a-z]{5}(?![0-9a-z])/);});
