import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { emptyDir,runCli,treeSnapshot } from "./helpers.js";
import { initializeWorkspace } from "../src/core/workspace.js";
import { doctor } from "../src/core/doctor.js";

test("init creates only RESEARCH.md, four skills, and the two private directories",()=>{const root=emptyDir("init");initializeWorkspace(root);assert.deepEqual(fs.readdirSync(root).sort(),[".agents",".claude",".rsh","RESEARCH.md"]);assert.deepEqual(fs.readdirSync(path.join(root,".rsh")).sort(),["locks","records"]);assert.equal(fs.readFileSync(path.join(root,".rsh","locks",".gitignore"),"utf8"),"*\n!.gitignore\n");const relativeSkills=[".agents",".claude"].flatMap(b=>["rsh-resume","rsh-checkpoint"].map(n=>path.join(b,"skills",n,"SKILL.md")));assert.deepEqual(treeSnapshot(root).map(([file])=>file).sort(),["RESEARCH.md",...relativeSkills].sort());relativeSkills.forEach(file=>assert.match(fs.readFileSync(path.join(root,file),"utf8"),/^---\nname: rsh-/));});
test("generated skills teach the result, replacement, and safe batch contracts",()=>{const root=emptyDir("skill-contract");initializeWorkspace(root);for(const parent of [".agents",".claude"]){const checkpoint=fs.readFileSync(path.join(root,parent,"skills","rsh-checkpoint","SKILL.md"),"utf8");for(const term of ["one main conclusion","Conclusion","Argument/Evidence","Scope","Reuse","[[relations]]","[assertion]","non-empty Markdown body","automatically adds `rsh:about`","structured `kind` and `body`","illegal C0 control characters","once per Record","semantic boundaries","never divide one theorem","Never generate or execute JavaScript or shell command strings","body_sha256","body_preview","rsh_replace","reserved `rsh:supersedes`"])assert.match(checkpoint,new RegExp(term.replaceAll("[","\\[").replaceAll("]","\\]")));const resume=fs.readFileSync(path.join(root,parent,"skills","rsh-resume","SKILL.md"),"utf8");for(const term of ["rsh:about","rsh:supersedes","latest active successor","superseded or withdrawn"])assert.match(resume,new RegExp(term));}});
test("init refuses incompatible managed skills and doctor checks their contract",()=>{const root=emptyDir("stale-skill"),target=path.join(root,".agents","skills","rsh-checkpoint","SKILL.md");fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,"stale\n");assert.throws(()=>initializeWorkspace(root),/incompatible content/);assert.equal(fs.existsSync(path.join(root,"RESEARCH.md")),false);assert.equal(fs.existsSync(path.join(root,".rsh")),false);fs.rmSync(path.join(root,".agents"),{recursive:true});initializeWorkspace(root);fs.writeFileSync(path.join(root,".agents","skills","rsh-checkpoint","SKILL.md"),"stale\n");const report=doctor(root);assert.equal(report.ok,false);assert.match(report.errors.map(x=>x.detail).join("\n"),/does not match the generated contract/);});
test("repeated init refuses without overwriting",()=>{const root=emptyDir("repeat");initializeWorkspace(root);fs.appendFileSync(path.join(root,"RESEARCH.md"),"custom\n");const before=treeSnapshot(root);assert.throws(()=>initializeWorkspace(root),/already initialized|refusing to overwrite/);assert.deepEqual(treeSnapshot(root),before);});
test("missing rg makes init zero-write and doctor reports only that prerequisite",()=>{const root=emptyDir("no-rg");const env={PATH:path.dirname(process.execPath)};const result=runCli(root,["init"],{env,success:false});assert.notEqual(result.status,0);assert.match(result.stderr,/requires ripgrep/);assert.deepEqual(fs.readdirSync(root),[]);initializeWorkspace(root);const old=process.env.PATH;process.env.PATH=env.PATH;try{const report=doctor(root);assert.equal(report.ok,false);assert.deepEqual(report.errors.map(x=>x.name),["ripgrep"]);}finally{process.env.PATH=old;}});
test("init refuses managed symlink paths before writing core state",()=>{const root=emptyDir("symlink"),outside=emptyDir("outside");fs.symlinkSync(outside,path.join(root,".agents"),"dir");assert.throws(()=>initializeWorkspace(root),/unsafe skill path/);assert.equal(fs.existsSync(path.join(root,".rsh")),false);assert.equal(fs.existsSync(path.join(root,"RESEARCH.md")),false);});
