import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { tempWorkspace } from "./helpers.js";
import { commitFileBatch } from "../src/core/fs.js";
import { acquireWorkspaceWriteLock, withWorkspaceWriteLock } from "../src/core/write-lock.js";
const mod=new URL("../src/core/write-lock.js",import.meta.url).href;
function worker(root,trace,name){const script=`import fs from "node:fs";import{withWorkspaceWriteLock}from ${JSON.stringify(mod)};withWorkspaceWriteLock(${JSON.stringify(root)},()=>{fs.appendFileSync(${JSON.stringify(trace)},"start ${name}\\n");Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,80);fs.appendFileSync(${JSON.stringify(trace)},"end ${name}\\n")},{timeoutMs:5000});`;return new Promise((resolve,reject)=>{const c=spawn(process.execPath,["--input-type=module","--eval",script],{stdio:["ignore","ignore","pipe"]});let stderr="";c.stderr.on("data",chunk=>{stderr+=chunk});c.on("error",reject);c.on("exit",code=>code===0?resolve():reject(new Error(`worker ${code}: ${stderr.trim()}`)));});}
test("write lock serializes processes and releases on throw",async()=>{const root=tempWorkspace("lock"),trace=path.join(os.tmpdir(),`rsh-trace-${process.pid}-${Date.now()}`);await Promise.all([worker(root,trace,"a"),worker(root,trace,"b")]);const lines=fs.readFileSync(trace,"utf8").trim().split("\n");assert.equal(lines.length,4);assert.equal(lines[1],`end ${lines[0].slice(6)}`);assert.equal(lines[3],`end ${lines[2].slice(6)}`);assert.notEqual(lines[0],lines[2]);assert.throws(()=>withWorkspaceWriteLock(root,()=>{throw new Error("boom")}),/boom/);assert.equal(fs.existsSync(path.join(root,".rsh","locks","write.lock")),false);});
test("write lock contenders tolerate a holder releasing during acquisition",async()=>{const root=tempWorkspace("lock-race"),trace=path.join(os.tmpdir(),`rsh-race-${process.pid}-${Date.now()}`),names=Array.from({length:8},(_,index)=>String(index));await Promise.all(names.map(name=>worker(root,trace,name)));const lines=fs.readFileSync(trace,"utf8").trim().split("\n");assert.equal(lines.length,names.length*2);for(let index=0;index<lines.length;index+=2)assert.equal(lines[index+1],`end ${lines[index].slice(6)}`);assert.deepEqual(new Set(lines.filter((_,index)=>index%2===0).map(line=>line.slice(6))),new Set(names));});
test("write lock retries when an EEXIST holder disappears before inspection",()=>{const root=tempWorkspace("lock-release-race"),lockPath=path.join(root,".rsh","locks","write.lock"),originalLink=fs.linkSync;fs.writeFileSync(lockPath,"seed\n");let injected=false;fs.linkSync=(source,target)=>{if(!injected&&target===lockPath){injected=true;fs.rmSync(lockPath);const error=new Error("simulated released holder");error.code="EEXIST";throw error;}return originalLink(source,target);};try{const release=acquireWorkspaceWriteLock(root,{timeoutMs:1000});assert.equal(injected,true);release();assert.equal(fs.existsSync(lockPath),false);}finally{fs.linkSync=originalLink;fs.rmSync(lockPath,{force:true});}});
test("batch commit rolls back earlier replacement after later failure",()=>{const root=tempWorkspace("rollback"),first=path.join(root,"first.txt"),bad=path.join(root,"occupied");fs.writeFileSync(first,"before");fs.mkdirSync(bad);assert.throws(()=>commitFileBatch([{target:first,contents:"after"},{target:bad,contents:"bad"}]));assert.equal(fs.readFileSync(first,"utf8"),"before");assert.equal(fs.statSync(bad).isDirectory(),true);assert.equal(fs.readdirSync(root).some(n=>n.includes(".txn-")||n.includes(".backup-")),false);});
